services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NODE_VERSION: "22"
        PNPM_VERSION: "10.11.1"
    working_dir: /app/apps/web
    command: pnpm dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    env_file:
      - .env
      - .env.local

#   api:
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#     ports:
#       - '3001:3001'
#     environment:
#       - NODE_ENV=development
#     volumes:
#       - .:/app
#       - node_modules:/app/node_modules
#     env_file:
#       - .env
#       - .env.local

#   postgres:
#     image: postgres
#     ports:
#       - '54320:5432'
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_DB: seattle_lakes_database # THIS MUST MATCH YOUR DB NAME IN .env
#       POSTGRES_HOST_AUTH_METHOD: trust
#     env_file:
#       - .env
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  node_modules:
