FROM node:22.12.0-alpine AS base

# Install dependencies and build tools
# `--no-cache` avoids caching and ensures we get the latest package versions
RUN apk add --no-cache \
    # Required by node-gyp for native modules like sharp
    libc6-compat \
    # Required by node-gyp for native modules like sharp
    python3 \
    # Required by node-gyp for native modules like sharp
    py3-setuptools \
    # Required by node-gyp for native modules like sharp
    make \
    # Required by node-gyp for native modules like sharp
    g++ \
    # Required by node-gyp for native modules like sharp
    gcc

# Set Python path for node-gyp
ENV PYTHON=/usr/bin/python3

# Install pnpm and next globally
RUN npm install -g pnpm@8.15.4 next

WORKDIR /app

# First copy package files
COPY package.json pnpm-lock.yaml* pnpm-workspace.yaml* ./
COPY apps/web/package.json ./apps/web/package.json

# Copy the rest of the application
COPY . .

# Install all dependencies (root + workspaces) and TypeScript types
RUN pnpm install --no-frozen-lockfile -r && \
    cd apps/web && \
    pnpm add --save-exact --save-dev @types/react @types/node && \
    cd /app && \
    pnpm store prune --store /root/.local/share/pnpm/store

# Set working directory to the web package
WORKDIR /app/apps/web

EXPOSE 3000

CMD ["pnpm", "dev"]
