name: Setup Branch Protection

on:
  push:
    branches: [staging, production]  # Now includes both staging and production branches
  workflow_dispatch:    # Allow manual triggering

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install

      - name: Set up GitHub Token
        id: auth
        run: echo "token=${{ secrets.GITHUB_TOKEN || secrets.PAT }}" >> $GITHUB_ENV

      - name: Set branch protection
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const branch = context.ref.replace('refs/heads/', '');
            
            // Common protection settings
            const protectionSettings = {
              owner,
              repo,
              branch,
              required_status_checks: {
                strict: true,
                contexts: ['lint', 'test', 'build']
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true
              },
              restrictions: null,
              required_linear_history: true,
              allow_force_pushes: false,
              allow_deletions: false
            };

            // Add additional protection for production branch
            if (branch === 'production') {
              protectionSettings.required_pull_request_reviews.required_approving_review_count = 2;
            }

            try {
              await github.rest.repos.updateBranchProtection(protectionSettings);
              console.log(`Branch protection rules updated successfully for ${branch}`);
            } catch (error) {
              console.error(`Error updating branch protection for ${branch}:`, error);
              throw error;
            }