name: Setup Branch Protection

on:
  push:
    branches: [staging, production]
  workflow_dispatch:

# Add these permissions
permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GitHub Token
        id: auth
        run: echo "token=${{ secrets.PAT || secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Set branch protection
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const branch = context.ref.replace('refs/heads/', '');
            
            const protectionSettings = {
              owner,
              repo,
              branch,
              required_status_checks: {
                strict: true,
                contexts: ['lint', 'test', 'build']
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true
              },
              restrictions: null,
              required_linear_history: true,
              allow_force_pushes: false,
              allow_deletions: false
            };

            if (branch === 'production') {
              protectionSettings.required_pull_request_reviews.required_approving_review_count = 2;
            }

            try {
              await github.rest.repos.updateBranchProtection(protectionSettings);
              console.log(`✅ Branch protection rules updated for ${branch}`);
            } catch (error) {
              console.error(`❌ Error updating branch protection for ${branch}:`, error);
              throw error;
            }