name: Setup Environments

on:
  workflow_dispatch:

# Add necessary permissions
permissions:
  contents: write
  deployments: write
  id-token: write

jobs:
  setup-environments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create Staging Environment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.repos.createOrUpdateEnvironment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                environment_name: 'staging',
                wait_timer: 0,
                reviewers: [{
                  type: 'User',
                  id: '247720'
                }]
              });
              console.log('✅ Staging environment created/updated successfully');
            } catch (error) {
              console.error('❌ Error creating staging environment:', error);
              throw error;
            }

      - name: Create Production Environment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.repos.createOrUpdateEnvironment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                environment_name: 'production',
                wait_timer: 0,
                reviewers: [{
                  type: 'User',
                  id: '247720'
                }]
              });
              console.log('✅ Production environment created/updated successfully');
            } catch (error) {
              console.error('❌ Error creating production environment:', error);
              throw error;
            }