name: Setup Environments
on:
  workflow_dispatch:
jobs:
  setup-environments:
    runs-on: ubuntu-latest
    steps:
      - name: Create Staging Environment
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createOrUpdateEnvironment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              environment_name: 'staging',
              wait_timer: 0,
              reviewers: [{
                type: 'User',
                id: '247720'
              }]
            });
      - name: Create Production Environment
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createOrUpdateEnvironment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              environment_name: 'production',
              wait_timer: 0,
              reviewers: [{
                type: 'User',
                id: '247720'
              }]
            });